### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by sensito** [zbanga/FXCM_currency#5]
System: Ubuntu 16.4
python: 3
running in jupyter Notebook
File: TripleBarrier.ipynb
`NameError                                 Traceback (most recent call last)
<ipython-input-15-42086a0db8e5> in <module>
----> 1 data_in[cols].iplot()

NameError: name 'cols' is not defined`

File: Automated Algo.ipynb
`eyError                                  Traceback (most recent call last)
<ipython-input-12-bd850b7daa99> in <module>
----> 1 data.iplot()

~/anaconda3/lib/python3.7/site-packages/cufflinks/plotlytools.py in _iplot(self, kind, data, layout, filename, sharing, title, xTitle, yTitle, zTitle, theme, colors, colorscale, fill, width, dash, mode, interpolation, symbol, size, barmode, sortbars, bargap, bargroupgap, bins, histnorm, histfunc, orientation, boxpoints, annotations, keys, bestfit, bestfit_colors, mean, mean_colors, categories, x, y, z, text, gridcolor, zerolinecolor, margin, labels, values, secondary_y, secondary_y_title, subplots, shape, error_x, error_y, error_type, locations, lon, lat, asFrame, asDates, asFigure, asImage, dimensions, asPlot, asUrl, online, **kwargs)
   1156                                 sharing='private'
   1157         if sharing is None:
-> 1158                 sharing=auth.get_config_file()['sharing']
   1159 
   1160         if not filename:

KeyError: 'sharing'`

**Comment by zbanga** [comment]
You need to have an account with plotly
